(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJgALTMVIgBANQgBAOALAAIAxAAQAMAAABALIAACUQAAAHAEADQAFABAJAAQAKAAAEgBQAFgDAAgHIAAiUQgBgLAMAAIAyAAQALABAAgTQAAgRgMAAIifAAQgIAAgBAIgADSOMIBBBGQAHAJATgBQAOAAAEgEQAGgFgIgJIhOhVQgJgKAJgIIBAg7QAKgJgMgLQgMgMgNALIhKBDQgFAFgEABQgFADgLgBQgJABAAgNIAAg3QAAgMgSgBQgKAAgEACQgGADAAAIIAAC1QABAMAQAAQAVABAAgMIAAg8QAAgGAEgFQADgFAFAAQATABALAIgAhwOXQALAAAGAJIAfAxQAHAKARgBQAOAAAEgEQAFgEgFgIIgjgxQgDgGAHgHQAPgKAIgJQAPgQAAgXQAAgggVgTQgUgTggAAIhrAAQgKABABAHIAAC7QAAALAMAAIAPAAQAKgCAAgGIAAgxQgBgEAEgDQAEgDADAAgAmQOxQAHAAADAGIAOAbQADAJAPgBQAHAAAHgBQAJgEgDgGIhYi7QgEgJgMAAQgKAAgFAKIhZC5QgGAMAXAAQASAAACgIIAMgWQAFgLAJAAgArGNkIANBsQABAFAFADQAFADAFgBQAXAAgBgKIgVi2QgCgIgEgDQgDgCgGgBQgLABgEAHIg8BRQgHAIgDAAQgFgBgFgHIg5hPQgEgJgKAAQgLAAgEAFQgEADgBAJIgVCyQAAAFAGADQAFADAFgBQAUAAABgKIAPhqQAAgGAGgBQAEABACADIAtA8QAEAGAHAAQAGAAAEgFIAwg/QADgDAEgBQAFABACAGgAGyMbIAACvQAAAPAMAAICdAAQAKgBAAgQQAAgTgKAAIh6AAQgKAAAAgKIAAgfQAAgKALAAIBGAAQALAAgBgSQAAgSgKAAIhHAAQgKAAAAgJIAAgcQABgIAIgBIB6AAQAHABADgGQACgEAAgJQAAgJgCgDQgDgFgGAAIidAAQgMAAAAAOgAT4IxQgMAMAAATQAAASAMANQAOANARAAQATAAANgNQANgNAAgSQAAgTgNgMQgNgOgTAAQgRAAgOAOgAP5JKQAlAMA0AAQBUAAAzgsQAzgtgBhKQAAgggMgfQgMgegWgXQgUgVgXgSQgWgRgzgjIgqgeQgbgWgMgSQgJgLAAgXQAAgaARgPQASgQAdAAQAtAAAjAbQAOALAGAHQAHAHAOAVQAKAPAMAAQAKgBAIgFQAHgGAAgJQgBgIgBgEIgUhbQgGgZgSAAQgFABgDABIgKAGQgLAHgIAAIgMgBIgVgGQgkgIgmAAQhGAAgrAmQgrAmAAA9QAAA0AgAlQATAXASAOIBOA4QA/ArAbAdQAbAfABAhQgBAigZAVQgaAUgqAAQgkAAghgSQgigRgWgfIgMgRQgJgMgMAAQgMAAgHAHQgIAJAAALQAAAJACAIIAVBVQAFAPAFAGQAGAHALAAQAJAAALgIQAJgJAJAAIASAFgAjRF+QAHAAACALIABACQAYBeBGA2QBGA2BlABQCCgBBMhQQBMhRAAiIQAAiFhMhQQhMhQiAAAQhmAAhHA3QhGA2gYBfIgBABQgBAKgIABQgHABgCgMQgWhfhHg3QhIg3hpAAQh/AAhMBQQhLBRgBCIQAACFBNBRQBLBQB+AAQBogBBIg2QBGg2AYhfIABgCQACgKAGAAIABAAgAFmIeQgFAHAAAKQAAANAKAFQAGADAVADQBdANBrABQBGgBAwgOQAxgNAlgeQAugmAag9QAZg+AAhNQAAhFgUg4QgUg4glglQgngog0gSQg2gShPAAQhrAAhdANQgVADgGADQgKAGAAAMQAAALAFAGQAHAIAIgBIARAAQAKABAFAKQACALABAXIAAF5QgBAYgCAKQgFALgKAAIgRAAQgIAAgHAHgAyyIgQgGAGgBALQAAAOAJAFQAIAFAXAAICcAAQAXAAAKgFQAIgFABgOQgBgLgFgGQgHgIgKAAIgTAAQgMABgGgLQgCgHAAgbIAAiKQAAgZAIgGQAEgDAeAAIBGAAQAbAAAHADQAIAEACAMIAAAGQAEAWATAAQAOAAAFgJQAFgIAAgWIAAhIQAAgWgFgJQgFgJgOAAQgTAAgEAWIAAAEQgCANgIADQgHAEgbAAIhGAAQgdAAgFgDQgIgGAAgZIAAhkQgBgjAJgIQAIgJAjAAIBtAAQAgAAAMAEQAQAFAFAQQAFANAEAFQAHANAOAAQANAAAFgIQAEgJgDgRIgMg6QgFgWgaABIlvAAQgWgBgJAGQgIAFgBAOQABAKAGAHQAHAHAJAAIARAAQAEAAAEADQAEAEABAFQAEALAAAXIAAF7QAAAYgDAKQgEALgKgBIgRAAQgJAAgHAIgACnrWQADAJgKADQgoAOgmATQgmATgYATQg6AngfBDQghBDAABZQAACLBPBUQBOBUCEAAQCHAABQhUQBQhVgBiOQABikhphOQg7gsg3AGQgiAEgFATQgEAUAaAKQA2AUAZA7QAXA4AABfQAABwgqBCQgrBChJAAQhMAAgphAQgrhBAAhxQAAhRAQgyQATg/AvgvQAegdBGgjQA+geAigsQAUgZAAgVQABgTgPgFQgMgDgNAMIgYAXQgvAfg4gTQgugOglgpQgbgfgogIQgcgGggAHQgKADgDgHQgEgHALgIQAcgVAqACQAvABAfAdQAeAbAgAPQAkAQAagEQARgDAAgPQAAgOgSgGQgggMgmg2Qglgzg1gQQhPgWhJA8QhDA4gYBWQgGAXALALQANALAUgJQA6gaAvAXQAJAEAhATQAcASAWAJQAsASA7gLIAGgBQAIAAABAIgAvDlQIBJDYQAHAYALAKQALAJATAAQATAAAKgLQALgMAJgeICHm0QAHgWAHgJQAIgJALgBQAjgFAAAxIAAF9QAAAbgCAHQgBAEgFADQgEADgFAAIgRAAQgIAAgHAHQgGAHAAAKQAAAOAIAFQAIAFAWAAICbAAQAUAAAIgFQAIgFAAgNQABgLgGgHQgGgHgJAAIgQAAQgLAAgGgKQgCgKAAgYIAAiBQABgdAFgHQAGgGAXgBIB0AAQAXABAGAHQADAEABAGIABAeIAAB8QAAAbgDAHQgGAKgJAAIgQAAQgJAAgHAHQgHAHAAAKQABAOAHAFQAJAFAWAAICaAAQAWAAAJgFQAIgFAAgOQAAgKgGgHQgGgHgJAAIgSAAQgFAAgDgDQgFgDgCgEQgCgLAAgXIAAl9QAAgYACgKQACgEAFgEQADgCAFAAIASAAQAIgBAHgGQAGgHAAgLQABgOgKgFQgIgFgWAAIiaAAQgWAAgJAFQgJAFAAAOQAAALAHAHQAGAGALABIAQAAQAKAAAFAKQADAGAAAcIAABoIgBAeQgBAHgDADQgGAIgXAAIh0AAQgXAAgGgHQgFgGgBgeIAAhtQAAgaACgIQAGgKALAAIAQAAQAJgBAGgGQAGgHAAgLQAAgOgIgFQgIgFgVAAIkmAAQgRAAgIAFQgHAHgBAMQABAVAbADQAdADAAASQABAJgEAMIheE6QgBAGgFAAQgEABgCgFIhfkuQgJgZABgKQAAgLAFgGQAGgEARgCQAbgEABgTQAAgXgdAAIinAAQgeAAABAZQAAAKAFAFQAFAFAOAEQAPADAGAFQAHAEADAJIAmBvQAHAXgJAZIg+C2QgCAGgFABQgEAAgCgGIhzlHQgDgKAAgJQgBgKAHgFQAGgFAOgBQARgCAGgEQAIgFAAgLQAAgXgcAAIiwAAQgcAAAAAWQAAAKAFAGQAFAFAOACQAUAEAHAIQAHAHAKAaICmG+QAJAZAKAJQALAJATAAQAQAAANgJQAGgHALgbIBMjYQACgEAFAAQADAAACAEgAOkiCQgGAHAAAKQAAAOAIAFQAJAGAVAAIFigBQAOAAAHgFQAHgFADgLIANhCQAEgQgFgJQgGgJgLAAQgPABgJAQIgHAPQgPAfgvAAIhVAAQgjAAgPgFQgKgEgDgLQgDgLAAgiIAAhrQAAgaAIgFQAEgDAfgBIAnAAQAaABAIADQAHADACANIABAGQAEAWASgBQAOABAFgJQAGgJgBgWIAAhIQABgWgGgIQgFgJgOAAQgTAAgDAVIgBAFQgCANgHADQgHAEgbAAIgnAAQgfAAgEgEQgIgEAAgaIAAhlQAAgiAJgJQAIgJAjAAIBPAAQAgABAMADQAPAGAHAPQAFAQADADQAHANAOgBQAMAAAGgIQAEgJgDgQIgMg7QgEgVgaAAIlTAAQgVAAgJAFQgJAGAAANQAAAKAGAHQAIAIAIgBIARAAQAEABAEADQAEADABAGQAEAIAAAZIAAF8QAAAagEAIQgBAFgDADQgEADgFAAIgRAAQgIAAgHAGgAHziCQgHAHAAAKQAAAOAIAFQAIAFAWAAIE/AAQAaAAAEgVIAOhCQADgQgFgJQgFgJgMAAQgPABgIAQIgIAPQgOAfgwAAIgwAAQgaABgLgCQgLgCgHgEQgHgFgCgJQgCgJAAgdIAAlkQAAgcACgGQADgLAPAAIASAAQAJAAAHgGQAHgHgBgLQAAgNgJgGQgIgFgXAAIidAAQgWAAgJAFQgJAGAAANQABALAGAHQAHAGAKAAIAQAAQALAAADALQADAJAAAZIAAGAQAAAXgDAIQgCAEgEAEQgEADgEAAIgQAAQgKAAgFAGg");
	this.shape.setTransform(0,1,0.17,0.17);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAZQgKgKAAgPQAAgOAKgLQAKgJAOgBQAPABAKAJQAKALAAAOQAAAPgKAKQgKALgPgBQgOABgKgLgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgUIAFAAIAOAUIAKAAg");
	this.shape_1.setTransform(22.1,11,0.17,0.17);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-1.9,15.4,0.17,0.17);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(22.2,10.8,0.17,0.17);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCtQgog+AAhsQAAhuAog/QApg/BFAAQBGAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_4.setTransform(-8.3,6.1,0.17,0.17);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgxQABgEADAAQADAAACAEIAZAyQABADgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-7.5,15.9,0.17,0.17);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(10.9,6.1,0.17,0.17);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCtQgog/AAhrQAAhuAog/QApg/BGAAQBFAAAqBAQApA+AABsQAABrgpA/QgpA/hGAAQhGAAgpg9g");
	this.shape_7.setTransform(1.2,6.1,0.17,0.17);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitelogo, new cjs.Rectangle(-29.7,-28.7,59.4,59.4), null);


(lib.wellmakethe = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbAgQgNgMAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgBQAFgCAEgDIADgCQAEgEADAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgCACIgGAGQgHAHgHACQgHADgJAAQgRAAgMgNg");
	this.shape.setTransform(56.8,3.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAMA+QgEgCAAgCQAAgEAEgCIAEgBQACgBAAgEIABgMQAAgcgDgHQgEgHgJAAQgEAAgEAEQgEACgCADQgCAFgBAGIgBAXQAAAKABACQAAABAAAAQABABAAAAQAAABABAAQAAABABAAIACABQAFACAAAEQAAACgEACQgFACgLgBQgNABgFgCQgEgCAAgEQAAgCAEgCIADAAQACgCABgEIABgMIAAgPIAAgNIAAgnIgCgLQgBgBgFgBQgGgBABgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQACgBAHgEIAJgCIAIgBQABAAAAABQABAAABAAQAAAAABAAQAAABAAAAIABAGIAAADIgBAiIAAAFIABACIACABIACgCIACgEQAEgEAFgCQAEgCAGAAQAPAAAHAJQAHAKAAATIABAIIAAAPIAAAFIAAAGIADAEIACAAQAFACAAACQAAAEgFACQgEACgOgBQgLABgEgCg");
	this.shape_1.setTransform(46.5,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgEA0QgEgCgDgCQgDgDgBgFIgBgSIAAgtIgJAAIgCgBIgBgCIAAgCQAAgDAKgHIADgEIADgCQAJgJADAAIACABIABACIAAAQIATAAIAEABIABAEIAAACIgBADIgEABIgSAAIgBABIAAACIAAAqQAAALACADQACACAEAAIAIgBIAGgBQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADQAAAFgIAEQgGAEgKABQgFgBgEgBg");
	this.shape_2.setTransform(38.1,2.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbAgQgNgMAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBQAAAAABAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgBQAFgCAEgDIADgCQAEgEADAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgCACIgGAGQgHAHgHACQgHADgJAAQgRAAgMgNg");
	this.shape_3.setTransform(24.9,3.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAcA/IgDgBQgEgBgIgKIgEgFIgCgCQgUgbgCAAIgBAAIgBAFIAAADIABASIACAHIAFACQAEACAAAEQAAACgFACQgDACgMgBQgNABgFgCQgDgCAAgEQAAgCADgCIADAAQACgCABgEIABgOIAAgMIAAgNIAAgJIgBghQAAgHgBgCIgGgCIgCgBIgDgBIgBgDQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQABgBAHgCIALgEIAJgBQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAIABAGIAAAQIgBAWIAAAWIABAEIABABIAEgCIAGgGIAIgHIACgEQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgCAAgDQAAgEADgBQAEgBANAAQAIAAAEABQAEACAAADQAAAEgHACQgGABgDACQgDABgHAHIgCABIgCAEIgBABQAAACAIAKIABABIAOASIAJAKIAIADQAGACAAADQAAAEgEACQgEACgJgBg");
	this.shape_4.setTransform(15.5,1.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAPApIgEgFIgEACQgKAHgKAAQgNAAgIgHQgIgHAAgNQAAgOAKgGQAKgIASAAQAEAAACABQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAEgFAAQgIAAgGAFQgFADAAAIQAAAHAFAEQAEAEAIAAQAHAAAEgEQAEgDAAgJIAAghQAAgHgEgEQgDgFgFABQgEAAgEACQgEABgDAEIgCADQgFAGgGAAQgDAAgCgCQgDgCAAgEQAAgIALgGQAKgFAPAAQAJAAAHADQAHACAEAEQACAEABAFIABASIAAAbIABAHQAAABABAAQAAABAAAAQAAAAABABQAAAAABAAIACABQAGABAAADQAAAEgGAEQgGADgIAAQgDAAgFgEg");
	this.shape_5.setTransform(5.4,3.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAgA9QgEgCAAgEQAAgDAFgCIAEgCQABgBABgEQABgEAAgMIAAgEIgBgkIAAgWIgLAdQgZBCgFAAQgDAAgFgJQgFgKgMgcIgTgqIgBAhIAAAXIABAQQAAAEACABIADACQAGACAAADQAAAEgFACQgEACgLgBQgJAAgEgCQgFgBAAgEQAAgCAFgDQAFgCAAgCIADgbIABgwIAAgCIgBgNQgBgDgBgBIgFgCQgFgCAAgEQAAgDAEgBQAEgCAMAAIANABIADAAQACACAGAPIAFANIACAFQAVAzABAAQACAAAIgSIASgwIACgGQADgJACgCIAFgDIAMgBQAMAAAEACQADABAAADQAAAEgEACIgDABQgCACgBADQgBADAAANIABAxIABAZQABACAEACIACABIADABIABADQAAAEgFACQgFACgOgBQgNABgFgCg");
	this.shape_6.setTransform(-7.5,1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOA+QgEgCAAgEQAAgCADgCIAFgCQABgCABgEIAAgSIAAgNIAAgPIAAgIQAAgVgBgGQAAgHgCgBIgFgBQgGgCABgDQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQACgBAGgCIAMgEIAIgBQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABAGIAAAHIgBA9IAAAdQABAGACACIAEACQAEACABAEQAAACgFACQgEACgMgBQgMABgEgCg");
	this.shape_7.setTransform(-23.3,1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgOA+QgEgCAAgEQAAgCAEgCIAEgCQACgCAAgEIAAgSIAAgNIAAgPIAAgIQAAgVgBgGQAAgHgCgBIgFgBQgGgCABgDQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQACgBAGgCIALgEIAIgBQABAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABAGIAAAHIgBA9IABAdQAAAGACACIAEACQAFACAAAEQgBACgEACQgEACgLgBQgNABgEgCg");
	this.shape_8.setTransform(-28.5,1.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAAAZIgHglIAAgBIAAgCQAAgEACgDQACgCADAAQAEAAACACQACACAAAFIAAACIAAABIgGAlg");
	this.shape_9.setTransform(-32.7,-2.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgbAgQgNgMAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgBQAFgCAEgDIADgCQAEgEADAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgCACIgGAGQgHAHgHACQgHADgJAAQgRAAgMgNg");
	this.shape_10.setTransform(-39.1,3.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAMAfIgSgwIgJgWQgEgIgDgCIgEgCQgFgCAAgEQAAgDAFgBQADgCARAAQAPAAAEACQAEABAAADQAAAEgGADIgBAAIgDACIgBADQAAADAEAMIAOAlIAGAOQABABAAAAQABABAAAAQABABAAAAQAAAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAgBABAAIAFgNIABgEQATgqgBgFIgBgFIgEgDIgBgBQgGgCAAgEQAAgDADgBQAEgCAOAAQAOAAADACQAEABAAADQAAAEgFACIgDACQgHAEgLAeIgIARIgQAoIgDAIQgFANgEAAQgFAAgMgggAgjA5IgBgDQgLgYgRgsIgIgVIgFgKQgCgDgDgCIgDgBQgFgCAAgEQAAgDAEgBQAEgCAQAAQARAAAEACQAEABAAADQAAAEgHADIgBAAIgCACIgBADQgBADAEAKIAPAlIAGAQQABABAAABQABAAAAABQAAAAABAAQAAAAABAAQABAAACgEIAEgKQACgFAEAAQAGgBAAAHIgBAEIgLAcIgDAHQgFANgEAAQgDAAgDgGg");
	this.shape_11.setTransform(-53,1.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethe, new cjs.Rectangle(-63.9,-11.2,127.8,24.6), null);


(lib.turkey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAJQgFgEAAgFQAAgFAFgEQAEgDAEAAQAGAAAEADQADAEAAAFQAAAFgDAEQgEAFgGAAQgEAAgEgFg");
	this.shape.setTransform(28.7,6.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgnA5QgEgEgBgFQAAgEADgDQADgEAFAAIAEABIACACIADADQABABAAABQAAAAABABQAAAAABABQAAAAABAAQAEAAAFgHQAEgGAAgHQAAgHgGgOIgBgCIgNgdIgIgRQgCgDgFgCIAAgBIgEgCIgBgDQAAgEAEgBQAFgCAMAAQANAAAEACQAEABAAADIAAADIgCACIgCABQgBABgBAAQgBAAAAABQgBAAAAAAQAAABAAAAIACAHIAHARIAGAQQACAEACAAQAAAAAAAAQAAAAABgBQAAAAABgBQAAgBABgBIAFgNIAGgSIADgIQgBgCgFgDQgEgDgBgCQABgDAEgBQAEgCAJAAQALAAAEACQADABAAADQAAAEgFABIgEABQgFADgFAOIgDAHIgKAbQgPAkgIALQgJALgMAAQgHAAgEgEg");
	this.shape_1.setTransform(21.7,4.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbAgQgNgMAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBQAAAAABAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgBQAFgCAEgDIADgCQAEgEADAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgCACIgGAGQgHAHgHACQgHADgJAAQgRAAgMgNg");
	this.shape_2.setTransform(12.3,3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcA/IgDgBQgEgBgIgKIgEgFIgCgCQgUgbgCAAIgBAAIgBAFIAAADIABASIACAHIAFACQAEACAAAEQAAACgFACQgDACgMgBQgNABgFgCQgDgCAAgEQAAgCADgCIADAAQACgCABgEIABgOIAAgMIAAgNIAAgJIgBghQAAgHgBgCIgGgCIgCgBIgDgBIgBgDQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQABgBAHgCIALgEIAJgBQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAIABAGIAAAQIgBAWIAAAWIABAEIABABIAEgCIAGgGIAIgHIACgEQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgCAAgDQAAgEADgBQAEgBANAAQAIAAAEABQAEACAAADQAAAEgHACQgGABgDACQgDABgHAHIgCABIgCAEIgBABQAAACAIAKIABABIAOASIAJAKIAIADQAGACAAADQAAAEgEACQgEACgJgBg");
	this.shape_3.setTransform(2.9,1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZArQgFgCABgEQAAgCADgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgFIAAgUQgBgFgDgBIgEgCQgEgBgBgDQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAFgDIAMgDIAIgCQAEAAABAMIAAABIAAABQAFgHAFgEQAFgDAEAAQAHAAADADQAEAEAAAGQAAAGgDADQgDAEgEAAIgFgBIgDgDIgDgDIgCgCQgFAAgDAIQgCAIAAAaQAAAHABAEQABAEACABIAEABQAEACAAADQABADgFACQgFABgLAAQgNAAgEgBg");
	this.shape_4.setTransform(-5.8,3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AATArIgBgDIAAgHIgBAAIgDACIgBABQgEAFgFABQgFACgGAAQgHAAgFgCQgGgCgEgFQgEgEgCgHQgBgIAAgRIAAgGIAAgGIAAgCQAAgHgBgCQgBgCgDgBIgEgCQgFgBAAgCQAAgBAAgBQABAAAAgBQAAAAAAgBQABAAAAgBIAIgDIAMgDIAJgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABAFIAAAEIgBAgQAAARAEAGQAEAHAIAAQAJAAAFgJQAEgJAAgUIAAgGQAAgHgBgCQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgDgCQgFgBAAgCQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAIgEIAMgDIAJgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABAFIAAAFIgBAjIAAAOIABAGQABAEAEABIACABQAFACAAACIgCADIgFAEIgMADIgKACQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBg");
	this.shape_5.setTransform(-14.9,3.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgRA+QgFgCAAgEQAAgEAFgBIAFgEQABgBAAgOIABgoIAAgXIgBgNIgCgEIgEgBIgFAAQgFABgEABIgGAFIgCAGIgCAFIgDADIgEABQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQgBgDAAgFQAAgLACgHQADgHAEAAIABAAIASABIAxAAIASgBIABAAQAEAAACAHQADAHABALQAAAFgCADQAAABgBAAQAAAAAAAAQgBABgBAAQAAAAgBAAIgCgBIgDgDIgDgFIgCgGQgDgDgEgCQgCgBgHgBIgDAAIgFABQAAABgBAAQAAAAAAAAQgBABAAAAQAAABAAABIAAANIgBAXIABAoQAAAOABABIAGAEQAEABAAAEQAAAEgEACQgGABgNAAQgNAAgEgBg");
	this.shape_6.setTransform(-26,1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.turkey, new cjs.Rectangle(-33.6,-11.2,67.2,24.6), null);


(lib.stuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAJQgFgEAAgFQAAgFAFgEQAEgDAEAAQAGAAAEADQADAEAAAFQAAAFgDAEQgEAFgGAAQgEAAgEgFg");
	this.shape.setTransform(31.6,6.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfA5QgLgHAAgKQAAgEACgDQACgDAFAAQAEAAACACQACACABAEQACAHAGADQAFAEALAAQAKAAAIgEQAHgFABgGQAAgFgEgCQgCgCgGAAIgKABIgMAAQgQAAgIgFQgIgFAAgHQAAgEADgEQADgEAGgEQgFgEgCgFQgDgGAAgHQAAgOALgJQAKgJARAAIAIAAIANADIAHgCIAJgFIADADIAAADQAAADgCAEQgDADgFADIADAHIABAHQAAAOgLAJQgKAIgRAAIgJgBIgIgBIgDADIAAADQAAAEAEACQAEACAJAAIAMgBIAOgBQALAAAHAFQAGAFAAAJQAAAOgOAJQgNAJgUAAQgQAAgLgGgAgOgqQgEAGAAAIQAAAJAEAFQAFAGAHAAQAHAAAEgGQAFgFAAgJQAAgJgEgFQgFgGgHAAQgGAAgGAGg");
	this.shape_1.setTransform(24.6,4.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgqArQgEgCAAgEQAAgCAEgCIACgBQACgBACgDIABgKIAAgFIAAgHIAAgIIgBgSQgBgEgCgBIgEgCQgFgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBIAGgDIAMgEIAJgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIABAEIAAAGIAAABIAAAAIABAAIAAAAIACgCIACgCQAKgIAKAAQAGAAAFACQAHADADAFQAEAEACAHQABAGABAOIAAALIAAAGIAAAFIAAAIQABADACABIADABQAEACAAACQAAAEgEACQgEABgNAAIgQgBQgFgCAAgDQAAgDAFgCIACgBQACgBACgEIABgNQgBgbgDgHQgDgHgKAAQgEAAgEADQgEADgCAEQgCAEgBAHIAAAXQAAAIAAADQABABAAAAQAAABAAAAQABABAAAAQABAAAAABIADABQAEACAAADQAAADgEACQgEABgLAAQgNAAgFgBg");
	this.shape_2.setTransform(14.2,3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgPA+QgEgCAAgEQAAgCAEgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgJIgBgRQgBgEgCgBIgEgCQgFgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIAFgDIANgEIAIgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIABAGIAAAFIAAAEIgBAVIAAAAIAAAWIAAALQABAEACABIADABQAFACAAADQAAADgFACQgEABgLAAQgMAAgFgBgAgKgrQgEgDAAgEQAAgFAFgEQAEgDAFAAQAFAAAEADQADADAAAFQAAAFgEADQgEADgFAAQgFAAgEgDg");
	this.shape_3.setTransform(6.1,1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXA+QgFgBAAgEQAAgCAFgCIACgBIACgEIABgKIAAgIIAAgpIgKAAIgCgBIgBgDIAAgDIABgDIACgBIAKAAIgBgGIgBgHQAAgNAJgHQAHgHAOAAQAKAAAGAEQAGAFAAAGQAAAFgCACQgDACgDAAQgEAAgCgCIgDgDIgCgDQgDgGgFAAQgEAAgBACQgBACAAADIABAKQABAHAAAGIANAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABADIAAADIgBADIgDABIgMAAIAAArIABAPQAAADACABIADABQAGACAAAEQgBADgEABQgEABgMAAQgNAAgDgBg");
	this.shape_4.setTransform(1.6,1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXA+QgFgBAAgEQAAgCAFgCIACgBIACgEIABgKIAAgIIAAgpIgKAAIgCgBIgBgDIAAgDIABgDIACgBIAKAAIgBgGIgBgHQAAgNAIgHQAJgHANAAQAJAAAHAEQAGAFAAAGQAAAFgCACQgDACgEAAQgCAAgDgCIgEgDIgBgDQgDgGgFAAQgEAAgBACQgCACAAADIACAKQABAHABAGIAMAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABADIAAADIgBADIgDABIgMAAIAAArIABAPQAAADACABIADABQAGACAAAEQgBADgEABQgEABgLAAQgNAAgEgBg");
	this.shape_5.setTransform(-3.7,1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AATArIgBgDIAAgHIgBAAIgDACIgBABQgEAFgFABQgFACgGAAQgHAAgFgCQgGgCgEgFQgEgEgCgHQgBgIAAgRIAAgGIAAgGIAAgCQAAgHgBgCQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgEgCQgFgBAAgCQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAgBIAIgDIAMgDIAJgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABAFIAAAEIgBAgQAAARAEAGQAEAHAIAAQAJAAAFgJQAEgJAAgUIAAgGQAAgHgBgCQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgDgCQgFgBAAgCQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAIgEIAMgDIAJgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABAFIAAAFIgBAjIAAAOIABAGQABAEAEABIACABQAFACAAACIgCADIgFAEIgMADIgKACQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBg");
	this.shape_6.setTransform(-12.5,3.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgDA0QgFgCgDgCQgDgDgCgFIgBgSIAAgtIgIAAIgCgBIgBgCIAAgCQAAgDAJgHIAEgEIADgCQAJgJADAAIACABIABACIAAAQIAUAAIACABIABAEIAAACIgBADIgCABIgSAAIgBABIgBACIAAAqQAAALACADQABACAFAAIAHgBIAHgBQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADQAAAFgHAEQgIAEgJABQgFgBgDgBg");
	this.shape_7.setTransform(-21,2.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUA+QgKgCgGgDQgEgDgCgHQgCgHAAgKQAAgEABgCQABgBAAAAQABAAAAgBQABAAAAAAQABAAABAAQAEAAAEAIIACAEQAGAJAGAFQAHADAJAAQAIAAAHgFQAGgGAAgHQAAgNgZgLIgCgBQgVgJgHgHQgHgIAAgMQAAgQAMgKQALgKASAAIAKABIALADIAEgCIADgBQAAAAABAAQABAAAAAAQAAABABAAQAAAAABAAIADAFIAFALQACAFAAAFQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAgBAAQAAAAgBAAQgEAAgFgGIgBgCQgFgGgFgDQgGgDgHAAQgJgBgGAFQgFAFAAAHQAAAIAEAEQAFAFASAIIADABQAQAHAHAFQAEAFADAGQACAFAAAHQAAASgMAJQgMAKgVAAQgLAAgJgCg");
	this.shape_8.setTransform(-29.5,1.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.stuffing, new cjs.Rectangle(-36.5,-11.2,73.1,24.6), null);


(lib.sides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAJQgEgEAAgFQAAgFAEgEQAFgDAEAAQAFAAAFADQADAEAAAFQAAAFgDAEQgFAFgFAAQgEAAgFgFg");
	this.shape.setTransform(21.6,6.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAtIgJgBIgCABIgDABIgCgBIgCgBQgDgDgCgGQgCgIgBgGQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQADABAFAGIADAGQADADAEACQAFACAEAAQAGAAADgDQADgCAAgGQAAgHgNgGIgGgDQgNgGgFgGQgFgFAAgIQABgMAHgGQAIgIANABIAFAAIAGAAIAEgBIADAAQAEgBAEAIQAEAGAAAHQAAAEgBACQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEgBIgEgHQgEgEgDgDQgEgCgEAAQgEAAgEADQgDADAAAEQAAAEADAEQADADALAFIABABQAXAKAAAOQAAAMgJAJQgJAIgOAAg");
	this.shape_1.setTransform(15.1,3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbAgQgNgMAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgBQAFgCAEgDIADgCQAEgEADAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgCACIgGAGQgHAHgHACQgHADgJAAQgRAAgMgNg");
	this.shape_2.setTransform(6.4,3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglA1QgKgMAAgTQAAgVAMgNQALgNATABIAFAAIAEACQABABAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAFgGgBIgCAAIgCAAQgKAAgFAIQgGAHAAANQAAAPAGAJQAHAJAJAAQAIAAAFgFQAFgFAAgJIAAgYIAAgnIgBgIQgBgDgDgBIgCgBQgGgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQACgCAHgDIAKgCIAIgBQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQABACAAADIAAAFIgBA0IABAkQAAAJACABIAGABQAEABAAAEQAAADgMAEIgJADIgGABIgEgBQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBIAAgEIAAgBIgBgCIgCADIgEADQgFADgEACQgFACgGAAQgQAAgKgLg");
	this.shape_3.setTransform(-3.4,1.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPA+QgEgCAAgEQAAgCAEgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgJIgBgRQgBgEgCgBIgEgCQgFgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIAFgDIANgEIAIgBQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIABAGIAAAFIAAAEIgBAVIAAAAIAAAWIAAALQABAEACABIADABQAFACAAADQAAADgFACQgEABgLAAQgMAAgFgBgAgKgrQgEgDAAgEQAAgFAFgEQAEgDAFAAQAFAAAEADQADADAAAFQAAAFgEADQgEADgFAAQgFAAgEgDg");
	this.shape_4.setTransform(-11.7,1.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUA+QgKgCgGgDQgEgDgCgHQgCgHAAgKQAAgEABgCQABgBAAAAQABAAAAgBQABAAAAAAQABAAABAAQAEAAAEAIIACAEQAGAJAGAFQAHADAJAAQAIAAAHgFQAGgGAAgHQAAgNgZgLIgCgBQgVgJgHgHQgHgIAAgMQAAgQAMgKQALgKASAAIAKABIALADIAEgCIADgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAIADAFIAFALQACAFAAAFQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAgBAAQAAAAgBAAQgEAAgFgGIgBgCQgFgGgFgDQgGgDgHAAQgJgBgGAFQgFAFAAAHQAAAIAEAEQAFAFASAIIADABQAQAHAHAFQAEAFADAGQACAFAAAHQAAASgMAJQgMAKgVAAQgLAAgJgCg");
	this.shape_5.setTransform(-19.5,1.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sides, new cjs.Rectangle(-26.5,-11.2,53.1,24.6), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARAkIgRg5IgQA5IgKAAIgWhGIALAAIAQA3IAQg3IAKAAIARA3IAQg3IAKAAIgUBGg");
	this.shape.setTransform(26.4,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgHgCgFgFQgFgFgDgHQgCgHgBgIQABgIACgGQADgHAFgFQAFgFAHgDIAHgCIAHAAQAIAAAHACIAHAEIAFAEQAFAFACAHQADAGAAAIQAAAIgDAHQgCAHgFAFIgFAEIgHADQgHADgIAAIgHgBgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFAEAEQADAEAFACQAFACAFAAQAGAAAFgCQAFgCADgEQAEgEACgFQACgFAAgGQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_1.setTransform(17.3,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARAkIgkg6IAAA6IgKAAIAAhGIANAAIAkA4IAAg4IAKAAIAABGg");
	this.shape_2.setTransform(9.2,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANAkIgRggIgKAAIAAAgIgKAAIAAhGIAXAAQAEAAAEABIAIADQAEADACADQACAEAAAGQAAAHgFAFQgCACgEABIgGACIATAhgAgOgEIALAAIAGAAIAFgCQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAAgBQACgCAAgCQAAgEgCgCIgDgDIgFgCIgFgBIgMAAg");
	this.shape_3.setTransform(0.1,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXAkIAAhGIAtAAIAAAJIgjAAIAAAUIAhAAIAAAIIghAAIAAAYIAkAAIAAAJg");
	this.shape_4.setTransform(-6.1,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeAkIAAhGIAYAAQAGAAAHACQAHACAFAEQAGAEADAHIADAIIAAAHIAAAJIgDAHIgEAGIgFAFQgFAEgHACIgNADgAgUAbIAMAAQAHAAAEgCIAJgFQAEgEADgEIABgGIABgGIgBgFIgBgGQgDgFgEgDIgJgFQgEgBgHAAIgMAAg");
	this.shape_5.setTransform(-12.9,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AANAkIgRggIgKAAIAAAgIgKAAIAAhGIAXAAQAEAAAEABIAIADQAEADACADQACAEAAAGQAAAHgFAFQgCACgEABIgGACIATAhgAgOgEIALAAIAGAAIAFgCQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAAgBQACgCAAgCQAAgEgCgCIgDgDIgFgCIgFgBIgMAAg");
	this.shape_6.setTransform(-19.6,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgHgCgFgFQgFgFgDgHQgDgHAAgIQAAgIADgGQADgHAFgFQAFgFAHgDIAHgCIAHAAQAIAAAHACIAHAEIAFAEQAFAFACAHQADAGAAAIQAAAIgDAHQgCAHgFAFIgFAEIgHADQgHADgIAAIgHgBgAgKgZQgFACgEAEQgDAEgCAFQgCAFAAAFQAAAGACAFQACAFADAEQAEAEAFACQAFACAFAAQAGAAAFgCQAFgCADgEQAEgEACgFQACgFAAgGQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_7.setTransform(-27.2,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-33.4,-8.1,67,16.3), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalebackground = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D6E47").s().p("A6bFUIAAqnMA04AAAIAAKng");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalebackground, new cjs.Rectangle(-169.2,-34,338.5,68), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A4hjqMAxDAAAIAAHVMgxDAAAg");
	this.shape.setTransform(0,0,1.016,1.043);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-25.5,321,51), null);


(lib.feast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAJQgDgEAAgFQAAgFADgEQAFgDAEAAQAFAAAEADQAFAEAAAFQAAAFgFAEQgEAFgFAAQgEAAgFgFg");
	this.shape.setTransform(21.9,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgEA0QgEgBgDgDQgDgDgCgFIAAgSIAAgtIgJAAIgCgBIgBgCIAAgCQAAgDAKgIIADgDIADgCQAJgJADABIACAAIABACIAAAQIATAAIAEABIABADIAAADIgBADIgEABIgSAAIgBABIAAACIAAAqQAAALACADQACACAEAAIAIgBIAGgBQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADQAAAEgIAFQgGAEgKABQgFgBgEgBg");
	this.shape_1.setTransform(16.1,1.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgGAtIgJgBIgDABIgCABIgCgBIgCgBQgCgDgDgGQgCgIAAgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAFABADAGIAEAGQACADAFACQAEACAEAAQAHAAACgDQAEgCAAgGQAAgHgOgGIgEgDQgOgGgFgGQgEgFgBgIQAAgMAJgGQAHgIAMABIAGAAIAGABIAEgCIACAAQAFAAAEAGQAEAHAAAHQAAAEgCACQAAAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEgBIgFgGQgDgFgEgDQgDgCgFAAQgDAAgDADQgEADAAAEQAAAFAEADQACADAKAFIABABQAZAKAAAOQAAAMgKAJQgJAHgOABg");
	this.shape_2.setTransform(8.8,2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAPApIgEgFIgEACQgKAHgKAAQgNAAgIgHQgIgIAAgMQAAgOAKgGQAKgIASAAQAEAAACABQABABAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAEgFAAQgIAAgGAFQgFADAAAIQAAAGAFAFQAEAEAIAAQAHAAAEgEQAEgDAAgJIAAghQAAgHgEgEQgDgFgFAAQgEABgEACQgEACgDADIgCADQgFAGgGAAQgDAAgCgCQgDgCAAgEQAAgIALgFQAKgGAPAAQAJAAAHADQAHACAEAEQACAEABAFIABASIAAAbIABAHQAAABABAAQAAABAAAAQAAAAABABQAAAAABAAIACABQAGABAAADQAAAEgGAEQgGADgIAAQgDAAgFgEg");
	this.shape_3.setTransform(0.2,2.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAhQgNgNAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgCQAFgBAEgDIADgCQAEgEADAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAACgCADIgGAHQgHAFgHADQgHADgJAAQgRAAgMgMg");
	this.shape_4.setTransform(-9.4,2.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrA+QgFgBAAgFQAAgDAFgBIAFgEQABgBABgNIABgiIgBgfQgBgOgBgBIgFgDQgFgCAAgDQAAgEAEgBQAEgBAPgBIA0AAIAJgBIAEgBIACABIACABIADAKIACAKQAAADgCADQAAABgBAAQAAAAAAABQgBAAgBAAQAAAAgBAAQgDAAgDgGIgDgEQgCgDgEgBQgDgBgGAAIgMAAIgMABQgEABgCABIgCAIIAAARIAAAGIAAAFIAEABIANAAQAHAAACgBQADgCABgGIAAgBQACgKAEABQAEAAABAEQACAFAAARQAAAPgCAFQgBAFgEAAQgEgBgCgIIAAgCQgBgFgDgCQgCgCgHgBIgNAAQgBAAAAABQgBAAAAAAQgBAAAAAAQAAABAAAAQgBABAAAGIAAAGIAAAZQABAFABABIAEACQAGACAAADQAAAFgFABQgFACgOgBQgNABgFgCg");
	this.shape_5.setTransform(-19.5,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.feast, new cjs.Rectangle(-26.8,-12.2,53.6,24.6), null);


(lib.desserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAJQgEgEgBgFQABgFAEgEQADgDAFAAQAGAAADADQAEAEAAAFQAAAFgEAEQgDAFgGAAQgFAAgDgFg");
	this.shape.setTransform(34.6,6.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAtIgJgBIgDABIgCABIgCgBIgCgBQgCgDgDgGQgCgIAAgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAEABAFAGIADAGQACADAFACQAFACADAAQAHAAACgDQAEgCAAgGQAAgHgOgGIgFgDQgNgGgFgGQgEgFAAgIQgBgMAJgGQAHgIAMABIAGAAIAGAAIAEgBIACAAQAFgBAEAIQAEAGAAAHQAAAEgCACQAAAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEgBIgFgHQgDgEgEgDQgDgCgFAAQgDAAgEADQgDADAAAEQAAAEADAEQAEADAJAFIABABQAZAKAAAOQAAAMgKAJQgJAIgOAAg");
	this.shape_1.setTransform(28.1,3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgDA0QgFgCgDgCQgDgDgCgFIgBgSIAAgtIgIAAIgCgBIgBgCIAAgCQAAgDAJgHIAEgEIADgCQAJgJADAAIACABIABACIAAAQIAUAAIACABIABAEIAAACIgBADIgCABIgSAAIgBABIgBACIAAAqQAAALACADQABACAGAAIAGgBIAGgBQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIABADQAAAFgHAEQgIAEgJABQgFgBgDgBg");
	this.shape_2.setTransform(21,2.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgZArQgFgCABgEQAAgCADgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgFIAAgUQgCgFgCgBIgDgCQgFgBgBgDQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAFgDIAMgDIAIgCQAEAAABAMIAAABIAAABQAFgHAFgEQAFgDAEAAQAGAAAEADQAEAEAAAGQAAAGgDADQgDAEgFAAIgEgBIgDgDIgDgDIgCgCQgFAAgDAIQgCAIAAAaQAAAHABAEQABAEACABIAEABQAEACAAADQABADgFACQgFABgLAAQgNAAgEgBg");
	this.shape_3.setTransform(14.4,3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAgQgNgMAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgBQAFgCAEgDIADgCQAEgEADAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgCACIgGAGQgHAHgHACQgHADgJAAQgRAAgMgNg");
	this.shape_4.setTransform(5.9,3.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgGAtIgJgBIgDABIgCABIgCgBIgCgBQgCgDgDgGQgDgIABgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAFABADAGIAEAGQADADAEACQAEACAEAAQAHAAACgDQAEgCAAgGQAAgHgOgGIgEgDQgOgGgFgGQgEgFgBgIQAAgMAIgGQAIgIAMABIAGAAIAGAAIAEgBIACAAQAFgBAEAIQAEAGAAAHQAAAEgBACQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEgBIgFgHQgDgEgEgDQgDgCgEAAQgFAAgCADQgEADAAAEQAAAEAEAEQACADAKAFIABABQAZAKgBAOQABAMgKAJQgJAIgOAAg");
	this.shape_5.setTransform(-2.8,3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGAtIgJgBIgDABIgCABIgCgBIgCgBQgCgDgDgGQgCgIAAgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAEABAEAGIAEAGQACADAFACQAFACADAAQAHAAACgDQAEgCAAgGQAAgHgOgGIgFgDQgNgGgFgGQgEgFAAgIQgBgMAJgGQAHgIAMABIAGAAIAGAAIAEgBIACAAQAFgBAEAIQAEAGAAAHQAAAEgCACQAAAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEgBIgFgHQgDgEgEgDQgDgCgFAAQgDAAgEADQgDADAAAEQAAAEADAEQAEADAJAFIABABQAZAKAAAOQAAAMgKAJQgJAIgOAAg");
	this.shape_6.setTransform(-10.6,3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgbAgQgNgMAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgBQAFgCAEgDIADgCQAEgEADAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAADgCACIgGAGQgHAHgHACQgHADgJAAQgRAAgMgNg");
	this.shape_7.setTransform(-19.3,3.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSA+IgLAAIgHAAIgHABQgLAAgDgCQgDgBAAgEQAAgEAEgBIAGgEQABgBABgNIAAghIAAggQgBgNgBgCIgGgDQgEgCAAgDQAAgDADgCQAEgCAKABIAIAAIAJAAIALAAIAKAAQAfAAASAQQARARAAAeQAAAdgSAQQgSAQghAAgAgSgxQgEACgBADIgCANIAAAaIAAAhIACAQQABACAFACQAGACAIAAQATAAAKgMQAKgMAAgYQAAgYgLgOQgMgOgUAAIgLABg");
	this.shape_8.setTransform(-30.9,1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.desserts, new cjs.Rectangle(-39.5,-11.2,79.1,24.6), null);


(lib.ctarectangleorange = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AltBeIAAi7ILbAAIAAC7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangleorange, new cjs.Rectangle(-36.6,-9.3,73.3,18.8), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ctarectangleorange();
	this.instance.parent = this;
	this.instance.setTransform(0.1,0.1,1.15,0.894,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-42.1,-8.3,84.3,16.8), null);


// stage content:
(lib.mobileleaderboardholidaymains = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_28 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_205 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(28).call(this.frame_28).wait(177).call(this.frame_205).wait(10));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,25.5,1.558,0.078,0,0,0,0.2,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(215));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(215));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(161,25.5,1.954,0.085,0,0,0,0.3,0);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.1,scaleX:1.95,scaleY:0.08,x:160.1,y:25,alpha:0},9).wait(206));

	// white-logo
	this.instance_2 = new lib.whitelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(281.9,23.4);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.02,scaleY:0.02,x:40},0).to({scaleX:1.08,scaleY:1.08,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(193));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AmFFfIAAq9IbRAAIAAK9g");
	mask.setTransform(135.6,35.1);

	// order-now
	this.instance_3 = new lib.ordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(130.1,36.6);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({x:-54.9},0).to({x:135.1,alpha:1},10,cjs.Ease.get(1)).to({x:130.1},8,cjs.Ease.get(1)).wait(182));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("ArhFfIAAq9MAkoAAAIAAK9g");
	mask_1.setTransform(160.7,27);

	// cta-rectangle
	this.instance_4 = new lib.ctarectangle();
	this.instance_4.parent = this;
	this.instance_4.setTransform(131.1,36.8);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(15).to({x:-53.9},0).to({x:136.1,alpha:1},10,cjs.Ease.get(1)).to({x:131.1},8,cjs.Ease.get(1)).wait(182));

	// feast
	this.instance_5 = new lib.feast();
	this.instance_5.parent = this;
	this.instance_5.setTransform(243.1,15.1);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(192).to({alpha:1},10).wait(13));

	// desserts
	this.instance_6 = new lib.desserts();
	this.instance_6.parent = this;
	this.instance_6.setTransform(255.8,14.1);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(152).to({alpha:1},10).wait(30).to({alpha:0},5).wait(18));

	// sides
	this.instance_7 = new lib.sides();
	this.instance_7.parent = this;
	this.instance_7.setTransform(242.8,14.1);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(112).to({alpha:1},10).wait(30).to({alpha:0},5).wait(58));

	// stuffing
	this.instance_8 = new lib.stuffing();
	this.instance_8.parent = this;
	this.instance_8.setTransform(252.8,14.1);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(72).to({alpha:1},10).wait(30).to({alpha:0},5).wait(98));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("ArXFfIAAq9MAkUAAAIAAK9g");
	mask_2.setTransform(159.7,27);

	// turkey
	this.instance_9 = new lib.turkey();
	this.instance_9.parent = this;
	this.instance_9.setTransform(249.9,14.1);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(24).to({x:6.9},0).to({x:254.9,alpha:1},10,cjs.Ease.get(1)).to({x:249.9},8,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(138));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("ArXFfIAAq9MAkUAAAIAAK9g");
	mask_3.setTransform(159.7,27);

	// well-make-the-turkey
	this.instance_10 = new lib.wellmakethe();
	this.instance_10.parent = this;
	this.instance_10.setTransform(151.5,14.1);
	this.instance_10.alpha = 0;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(24).to({x:-91.5},0).to({x:156.5,alpha:1},10,cjs.Ease.get(1)).to({x:151.5},8,cjs.Ease.get(1)).wait(173));

	// kale-background
	this.instance_11 = new lib.kalebackground();
	this.instance_11.parent = this;
	this.instance_11.setTransform(162.3,28.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(215));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(153.1,19.1,338.5,68);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;